### ISSUE TITLE
หลังจาก import เเล้ว มันขึ้น can't parse json object false T^T

### ISSUE THREAD

**Issue by chanathipjjj444** [CE-HOUSE/Auto-Login-KMITL-Mikrotik#1]
หลังจาก import เเล้ว มันขึ้น can't parse json object false ครับบบ ช่วยด้วยยยT^T

**Comment by BarwSirati** [comment]
ลองดูว่าได้ login ไว้ที่ไหนอีกบ้าง

**Comment by paleumm** [comment]
ไม่ก็ลองขยับขาโต๊ะดูครับ

**Comment by chanathipjjj444** [comment]
ลบ scheduler กับ script ออกตอนนี้ใส่ได้ละครับ

**Comment by chanathipjjj444** [comment]
> ลบ scheduler กับ script ออกตอนนี้ใส่ได้ละครับ

เเต่ยังใช้ไม่ได้เหมือนเดิม T T
