### ISSUE TITLE
Doesn't work on RouterOS v.7.13 anymore

### ISSUE THREAD

**Issue by Skul1CrowN** [CE-HOUSE/Auto-Login-KMITL-Mikrotik#2]
When update Mikrotik RouterOS v.7.13, it's doesn't work anymore.

Changelog on RouterOS v.7.13 (I think fetch method has been changed.)
*) fetch - added "http-auth-scheme" parameter, allows to select HTTP basic or digest authentication;
*) fetch - added "http-content-encoding" setting;
*) fetch - added raw logging;
*) fetch - allow to receive HTTP response headers;
*) fetch - require "ftp" user policy;

I'm try to fix this I will PR your repos when it finish or if this script only works on v.7.13 later I have already forked your repos for newer RouterOS version script.

**Comment by Skul1CrowN** [comment]
It's seem the bug with RouterOS not script when update to v.7.13.1 the script work normally.

**Comment by Skul1CrowN** [comment]
Script not re-login automatically or cannot fetch to login in v.7.13.1.

**Comment by BarwSirati** [comment]
Script can run on router os v.7.13.2
